
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfvnyztwjoumikbtaqnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpmdm55enR3am91bWlrYnRhcW5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NTY1NTMsImV4cCI6MjA1OTEzMjU1M30.sOgj9Lv1MLnVIn3Avn5NWMGAKFLt2_Nrcw7pzK_UD-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: 'pkce' // Use PKCE flow for better OAuth security
    }
  }
);
